.history file permission
ihwang/42sh pull request #84
Opened 2021-03-27 19:33 UTC by robkle

2021-03-27 23:48 UTC, xopxop requested changes

2021-03-27 23:48 UTC, xopxop commented on src/main.c
> +		exit(0);
exit shouldnt be 0, it has to be different than 0 because of error, can u change it to 1 and i will approve this change

2021-03-27 23:48 UTC, xopxop commented on src/features/history_management/history.c
> +		ft_printf("42sh: Fatal error: .history: Permission denied\n");
Use dprintf for printing error

2021-03-28 06:42 UTC, robkle commented on src/features/history_management/history.c
> +		ft_printf("42sh: Fatal error: .history: Permission denied\n");
Fixed and pushed

2021-03-28 12:21 UTC, xopxop requested changes

2021-03-28 12:21 UTC, xopxop commented on src/features/history_management/history.c
> +		ft_dprintf(0, "42sh: Fatal error: .history: Permission denied\n");
well, this need to be 2, 0 is not stderr :)) sr i gotta make u change again

2021-03-29 18:46 UTC, closed without merging